### ISSUE TITLE
ERROR: TypeError: can't convert String into Integer

### ISSUE THREAD

**Issue by gioppoluca** [CloudStack-extras/knife-cloudstack#4]
Both "knife cs server list" and "knife cs hosts" throw out that error.
cloudstack version 2.2.14
chef version 0.10.8
knife-cloudstack version 0.0.11

**Comment by franklouwers** [comment]
@sbotman bug seems very much alive in knife-cloudstack 0.0.18:

Steps to recreate:

1) Create a domain in CS that's not root, create a user in that domain, create api key and secret for that user.

2) knife cs server list -VV throws:

/Users/frank/.gem/ruby/2.1.3/gems/knife-cloudstack-0.0.18/lib/knife-cloudstack/connection.rb:117:in `[]': no implicit conversion of String into Integer (TypeError)
	from /Users/frank/.gem/ruby/2.1.3/gems/knife-cloudstack-0.0.18/lib/knife-cloudstack/connection.rb:117:in `get_server_public_ip'
	from /Users/frank/.gem/ruby/2.1.3/gems/knife-cloudstack-0.0.18/lib/chef/knife/cs_server_list.rb:86:in `block in run'
	from /Users/frank/.gem/ruby/2.1.3/gems/knife-cloudstack-0.0.18/lib/chef/knife/cs_server_list.rb:85:in `each'
	from /Users/frank/.gem/ruby/2.1.3/gems/knife-cloudstack-0.0.18/lib/chef/knife/cs_server_list.rb:85:in `run'
	from /Users/frank/.gem/ruby/2.1.3/gems/chef-11.18.6/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
	from /Users/frank/.gem/ruby/2.1.3/gems/chef-11.18.6/lib/chef/knife.rb:174:in `run'
	from /Users/frank/.gem/ruby/2.1.3/gems/chef-11.18.6/lib/chef/application/knife.rb:139:in `run'
	from /Users/frank/.gem/ruby/2.1.3/gems/chef-11.18.6/bin/knife:25:in `<top (required)>'
	from /Users/frank/.gem/ruby/2.1.3/bin/knife:23:in `load'
	from /Users/frank/.gem/ruby/2.1.3/bin/knife:23:in `<main>'

It does get the info from the server, but fails to parse.

**Comment by sbotman** [comment]
Tnx for the info Frank. Will test with a user-account asap! Or if you have the solution, i will be happy to merge any PR :)

Gr Sander

**Comment by franklouwers** [comment]
It's more complex it seems, has to do with 

     "nic"=>[],

in return (I just stumble upon this because the only VM I have without nic, is one in a tenant domain). Will see if I can fix and will PR

**Comment by sbotman** [comment]
Tnx!

**Comment by sbotman** [comment]
@franklouwers did some testing and all seemed just find. I have pushed out a new gem, so you can update towards version 0.0.19! Again thanks for helping out!
