### ISSUE TITLE
knife cs stack create ignores --cloudstack-api-key/--cloudstack-secret-key options

### ISSUE THREAD

**Issue by asako-toyama** [CloudStack-extras/knife-cloudstack#98]
when knife.rb setting default api key/secret key of cloudstack user's,  "knife cs stack create" picks them up and ignores CLI options.  Other knife cs commands user CLI options before default setting in knife.rb.  why?  I suspect it's a bug...?

**Comment by sbotman** [comment]
@asako-toyama did you had any chance to test this?

**Comment by sbotman** [comment]
Closing because I assume this is fixed within master. Please feel free to reopen the ticket if this is not the case.
